### ISSUE TITLE
Map with object key is not supported

### ISSUE THREAD

**Issue by zigzago** [jershell/kbson#6]
See https://github.com/Litote/kmongo/blob/master/kmongo-serialization-mapping/src/test/kotlin/SerializationCodecTest.kt#L78 for a test sample.

The stacktrace:

```
kotlinx.serialization.SerializationException: map key name is not primitive

	at com.github.jershell.kbson.BsonEncoder.encodeElement(BsonEncoder.kt:97)
	at kotlinx.serialization.ElementValueEncoder.encodeSerializableElement(ElementWise.kt:82)
	at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:133)
```

**Comment by jershell** [comment]
I added it. Please check result too
