### ISSUE TITLE
Set serialization is not supported

### ISSUE THREAD

**Issue by zigzago** [jershell/kbson#7]
See a test case here: https://github.com/Litote/kmongo/blob/master/kmongo-serialization-mapping/src/test/kotlin/SerializationCodecTest.kt#L64

And the stacktrace:
```

java.lang.IllegalArgumentException: Size must be known in advance when using READ_ALL

	at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:35)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
	at com.github.jershell.kbson.BsonDocumentDecoder.decodeSerializableValue(BsonDocumentDecoder.kt:46)
	at kotlinx.serialization.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:245)
	at kotlinx.serialization.TaggedDecoder.tagBlock(Tagged.kt:258)
	at kotlinx.serialization.TaggedDecoder.decodeSerializableElement(Tagged.kt:245)
```

**Comment by jershell** [comment]
I did it. Please check result
